namespace Lucid.Services.Infrastructure.Events;

// ── Base contract ─────────────────────────────────────────────────────────────

/// <summary>
/// Base record for all strongly-typed events published through the Lucid
/// event bus. Events are immutable value objects — do not add mutable state.
///
/// Derived records should be <c>sealed</c> and named with an "Event" suffix,
/// e.g. <c>TelemetryUpdatedEvent</c>.
///
/// All events are published with UTC timestamps. Never put user-sensitive
/// data directly in an event — pass identifiers and let subscribers query
/// if needed.
/// </summary>
public abstract record OperationalEvent
{
    /// <summary>Globally unique identifier for this event instance.</summary>
    public Guid EventId { get; init; } = Guid.NewGuid();

    /// <summary>UTC time the event was created by the publisher.</summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Optional correlation ID that links this event to a broader workflow,
    /// session, or causal chain. Set by publishers that participate in
    /// correlated workflows.
    /// </summary>
    public string? CorrelationId { get; init; }

    /// <summary>Publisher-assigned priority hint for handler ordering.</summary>
    public EventPriority Priority { get; init; } = EventPriority.Normal;

    /// <summary>Human-readable source category (e.g. "Telemetry", "Execution").</summary>
    public string? Source { get; init; }
}

// ── Telemetry domain ──────────────────────────────────────────────────────────

/// <summary>
/// Published each time the telemetry engine completes a new snapshot cycle.
/// </summary>
public sealed record TelemetrySnapshotReadyEvent : OperationalEvent;

/// <summary>
/// Published when a new insight is generated by the intelligence engine.
/// </summary>
/// <param name="InsightId">Stable identifier of the generated insight.</param>
/// <param name="Category">High-level category (e.g. "Performance", "Forecast").</param>
/// <param name="Severity">Severity level as a string (mirrors InsightSeverity).</param>
public sealed record InsightGeneratedEvent(
    string InsightId,
    string Category,
    string Severity) : OperationalEvent;

/// <summary>Published when a previously active insight is resolved or cleared.</summary>
/// <param name="InsightId">Identifier of the cleared insight.</param>
public sealed record InsightClearedEvent(string InsightId) : OperationalEvent;

// ── Execution domain ──────────────────────────────────────────────────────────

/// <summary>Published when an action executor begins work.</summary>
/// <param name="ActionId">Unique ID for this execution attempt.</param>
/// <param name="ActionType">The executor type name (e.g. "TempFileCleanup").</param>
/// <param name="IsDryRun">Whether the action is running in preview mode.</param>
public sealed record ActionExecutionStartedEvent(
    string ActionId,
    string ActionType,
    bool   IsDryRun) : OperationalEvent;

/// <summary>Published when an action executor finishes, successfully or not.</summary>
/// <param name="ActionId">Matches the ID from the corresponding Started event.</param>
/// <param name="ActionType">The executor type name.</param>
/// <param name="Succeeded">Whether the action completed without error.</param>
/// <param name="ErrorMessage">Non-null only when <paramref name="Succeeded"/> is false.</param>
public sealed record ActionExecutionCompletedEvent(
    string  ActionId,
    string  ActionType,
    bool    Succeeded,
    string? ErrorMessage = null) : OperationalEvent;

/// <summary>Published when a rollback is triggered for a previously completed action.</summary>
/// <param name="ActionId">ID of the action being rolled back.</param>
/// <param name="ActionType">The executor type name.</param>
public sealed record ActionRollbackEvent(
    string ActionId,
    string ActionType) : OperationalEvent;

// ── Workflow domain ───────────────────────────────────────────────────────────

/// <summary>Published when a multi-step operational workflow begins.</summary>
/// <param name="WorkflowId">Unique workflow instance identifier.</param>
/// <param name="WorkflowType">Descriptor of the workflow kind (e.g. "FileOrganization").</param>
public sealed record WorkflowStartedEvent(
    string WorkflowId,
    string WorkflowType) : OperationalEvent;

/// <summary>Published when a workflow reaches a named checkpoint.</summary>
/// <param name="WorkflowId">Parent workflow identifier.</param>
/// <param name="Checkpoint">Name of the checkpoint reached.</param>
public sealed record WorkflowCheckpointEvent(
    string WorkflowId,
    string Checkpoint) : OperationalEvent;

/// <summary>Published when a workflow finishes (success or failure).</summary>
/// <param name="WorkflowId">Workflow instance identifier.</param>
/// <param name="WorkflowType">Workflow kind descriptor.</param>
/// <param name="Succeeded">Completion status.</param>
public sealed record WorkflowCompletedEvent(
    string WorkflowId,
    string WorkflowType,
    bool   Succeeded) : OperationalEvent;

// ── Trust / consent domain ────────────────────────────────────────────────────

/// <summary>Published when an operation requires explicit user consent before proceeding.</summary>
/// <param name="OperationId">Identifier for the pending operation.</param>
/// <param name="Description">Human-readable explanation of what is being requested.</param>
public sealed record ConsentRequestedEvent(
    string OperationId,
    string Description) : OperationalEvent;

/// <summary>Published when the user grants consent for a pending operation.</summary>
/// <param name="OperationId">Matches the ID from the corresponding Request event.</param>
public sealed record ConsentGrantedEvent(string OperationId) : OperationalEvent;

/// <summary>Published when the user denies consent for a pending operation.</summary>
/// <param name="OperationId">Matches the ID from the corresponding Request event.</param>
public sealed record ConsentDeniedEvent(string OperationId) : OperationalEvent;

// ── Session domain ────────────────────────────────────────────────────────────

/// <summary>Published when a new operational session begins.</summary>
/// <param name="SessionId">Unique session identifier.</param>
public sealed record SessionStartedEvent(string SessionId) : OperationalEvent;

/// <summary>Published when a session ends.</summary>
/// <param name="SessionId">Identifier of the ended session.</param>
/// <param name="Duration">Total elapsed duration of the session.</param>
public sealed record SessionEndedEvent(
    string   SessionId,
    TimeSpan Duration) : OperationalEvent;

// ── Diagnostics domain ────────────────────────────────────────────────────────

/// <summary>Published when a service's health state changes.</summary>
/// <param name="ServiceName">Logical name of the reporting service.</param>
/// <param name="IsHealthy">New health state.</param>
/// <param name="Reason">Optional human-readable reason for the change.</param>
public sealed record ServiceHealthChangedEvent(
    string  ServiceName,
    bool    IsHealthy,
    string? Reason = null) : OperationalEvent;

/// <summary>Published when the platform enters degraded mode.</summary>
/// <param name="Reason">Why degraded mode was activated.</param>
public sealed record DegradedModeActivatedEvent(string Reason) : OperationalEvent;

/// <summary>Published when the platform exits degraded mode and resumes normal operation.</summary>
public sealed record DegradedModeDeactivatedEvent : OperationalEvent;

// ── Simulation domain ─────────────────────────────────────────────────────────

/// <summary>Published when an operational simulation run begins.</summary>
/// <param name="SimulationId">Unique simulation run identifier.</param>
/// <param name="ScenarioName">Human-readable scenario description.</param>
public sealed record SimulationStartedEvent(
    string SimulationId,
    string ScenarioName) : OperationalEvent;

/// <summary>Published when a simulation run completes.</summary>
/// <param name="SimulationId">Simulation run identifier.</param>
/// <param name="Succeeded">Whether the simulation finished without error.</param>
public sealed record SimulationCompletedEvent(
    string SimulationId,
    bool   Succeeded) : OperationalEvent;

// ── Conversation domain ───────────────────────────────────────────────────────

/// <summary>Published when a new conversation turn begins processing.</summary>
/// <param name="SessionId">Companion session identifier.</param>
public sealed record ConversationTurnStartedEvent(string SessionId) : OperationalEvent;

/// <summary>Published when a conversation turn has been fully processed.</summary>
/// <param name="SessionId">Companion session identifier.</param>
/// <param name="ResolvedIntent">The intent that was resolved from the user's input.</param>
public sealed record ConversationTurnCompletedEvent(
    string  SessionId,
    string? ResolvedIntent) : OperationalEvent;
