using Lucid.Services.Intelligence;
using Lucid.Services.Infrastructure.OperationalState;
using Lucid.Services.Reasoning.Context;

namespace Lucid.Services.Reasoning.Cognitive;

/// <summary>
/// Aggregated snapshot of all operational signals available for one reasoning cycle.
///
/// The <see cref="ICognitiveReasoningEngine"/> builds a <see cref="ReasoningContext"/>
/// at the start of each cycle by pulling the latest state from all registered signal
/// sources. The context is then passed through each inference rule immutably.
///
/// Design:
///   - Immutable record — reasoning rules receive a consistent view of the world
///   - Built once per cycle, discarded after inference is complete
///   - Never holds references to mutable service state — snapshots only
/// </summary>
public sealed record ReasoningContext
{
    /// <summary>UTC time this context snapshot was assembled.</summary>
    public DateTime AssembledAt { get; init; } = DateTime.UtcNow;

    // ── System metrics ────────────────────────────────────────────────────────

    /// <summary>Current CPU utilization (0–100).</summary>
    public double CpuPercent { get; init; }

    /// <summary>Current RAM utilization (0–100).</summary>
    public double RamPercent { get; init; }

    /// <summary>Current GPU utilization (0–100). 0 if GPU monitoring unavailable.</summary>
    public double GpuPercent { get; init; }

    /// <summary>Current disk I/O throughput in MB/s. 0 if unavailable.</summary>
    public double DiskThroughputMbps { get; init; }

    /// <summary>Current CPU temperature in °C. 0 if thermal monitoring unavailable.</summary>
    public double CpuTemperatureCelsius { get; init; }

    /// <summary>Number of seconds the machine has been running since last boot.</summary>
    public long UptimeSeconds { get; init; }

    // ── Trend indicators (from history buffer) ────────────────────────────────

    /// <summary>CPU trend over the last 5 minutes: positive = rising, negative = falling.</summary>
    public double CpuTrend5Min { get; init; }

    /// <summary>RAM trend over the last 5 minutes.</summary>
    public double RamTrend5Min { get; init; }

    /// <summary>Thermal trend over the last 5 minutes.</summary>
    public double ThermalTrend5Min { get; init; }

    // ── Active intelligence findings ──────────────────────────────────────────

    /// <summary>Active insights currently generated by the intelligence engine.</summary>
    public IReadOnlyList<SystemInsight> ActiveInsights { get; init; } = [];

    /// <summary>Count of active insights by severity (key = severity string).</summary>
    public IReadOnlyDictionary<string, int> InsightsBySeverity { get; init; } =
        new Dictionary<string, int>();

    // ── Platform state ────────────────────────────────────────────────────────

    /// <summary>Current platform operational state snapshot from Phase 18.</summary>
    public OperationalStateSnapshot OperationalState { get; init; } =
        OperationalStateSnapshot.Empty;

    // ── Workload context ──────────────────────────────────────────────────────

    /// <summary>
    /// Contextual interpretation of what the system is currently doing.
    /// Produced by <see cref="IOperationalContextSynthesizer"/>.
    /// Null on the first cycle before context is established.
    /// </summary>
    public ContextProfile? CurrentContext { get; init; }

    // ── Session ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Seconds since the current user session started.
    /// Used to distinguish startup transients from sustained conditions.
    /// </summary>
    public double SessionAgeSeconds { get; init; }

    /// <summary>True if the system was started within the last 5 minutes.</summary>
    public bool IsPostBoot => UptimeSeconds < 300;

    /// <summary>True if the session just started (< 2 minutes old).</summary>
    public bool IsEarlySession => SessionAgeSeconds < 120;

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>Returns true if CPU has been elevated for a sustained period.</summary>
    public bool HasSustainedHighCpu =>
        CpuPercent > 75 && CpuTrend5Min > 0;

    /// <summary>Returns true if RAM pressure is both high and rising.</summary>
    public bool HasRisingRamPressure =>
        RamPercent > 80 && RamTrend5Min > 1.5;

    /// <summary>Returns true if thermal readings indicate thermal stress.</summary>
    public bool HasThermalStress =>
        CpuTemperatureCelsius > 80;

    /// <summary>Returns true if the system is under high combined resource pressure.</summary>
    public bool IsUnderSignificantLoad =>
        CpuPercent > 70 || RamPercent > 80 || GpuPercent > 80;
}
