$ErrorActionPreference = "Stop"

function Write-Section([string]$message) {
    Write-Host "`n>>> $message" -ForegroundColor Cyan
}

function Write-Detail([string]$message) {
    Write-Host "    $message" -ForegroundColor Gray
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$appDir = Join-Path $repoRoot "lucid-desktop\Lucid.App"
$projectPath = Join-Path $appDir "Lucid.App.csproj"

if (-not (Test-Path -LiteralPath $projectPath -PathType Leaf)) {
    throw "Project file not found: $projectPath"
}

[xml]$projectXml = Get-Content -LiteralPath $projectPath

$compileIncludes = @($projectXml.Project.ItemGroup.Compile | Where-Object { $_.Include })
$compileRemoves = @($projectXml.Project.ItemGroup.Compile | Where-Object { $_.Remove })
$pageRemoves = @($projectXml.Project.ItemGroup.Page | Where-Object { $_.Remove })

Write-Section "Check Lucid.App source inclusion policy"
Write-Detail "Project: $projectPath"
Write-Detail "Model: SDK default globbing; every project .cs file should compile unless generated by the SDK."

if ($compileIncludes.Count -gt 0) {
    Write-Section "Unexpected explicit Compile Include entries"
    foreach ($node in $compileIncludes) {
        Write-Host "    $($node.Include)" -ForegroundColor Red
    }

    throw "Lucid.App.csproj must not return to an explicit Compile Include allow-list."
}

if ($compileRemoves.Count -gt 0) {
    Write-Section "Unexpected Compile Remove entries"
    foreach ($node in $compileRemoves) {
        Write-Host "    $($node.Remove)" -ForegroundColor Red
    }

    throw "Lucid.App.csproj must not exclude managed source files from the SDK default glob."
}

if ($pageRemoves.Count -gt 0) {
    Write-Section "Unexpected Page Remove entries"
    foreach ($node in $pageRemoves) {
        Write-Host "    $($node.Remove)" -ForegroundColor Red
    }

    throw "Lucid.App.csproj must not exclude XAML pages or controls from the SDK default glob."
}

$sourceCount = @(Get-ChildItem -LiteralPath $appDir -Recurse -Filter *.cs -File |
    Where-Object { $_.FullName -notmatch '\\obj\\|\\bin\\' }).Count

Write-Section "Source-file inclusion check passed"
Write-Detail "Project source files covered by SDK default globbing: $sourceCount"
