namespace Lucid.Models;

/// <summary>
/// A single finding surfaced by the Intelligence Engine.
///
/// All text follows the "human language" rule from intelligence-engine.md:
///   GOOD: "Several startup apps are slowing your boot time."
///   BAD:  "Boot degradation threshold exceeded."
///
/// Phase 3: generated by the rules engine from correlated scan results.
/// Phase 1: static mock data.
/// </summary>
public sealed record SystemIssue(
    /// <summary>Short, plain-language title. One sentence max.</summary>
    string Title,

    /// <summary>One-paragraph explanation of what was found and why it matters.</summary>
    string Description,

    /// <summary>Severity level (per intelligence-engine.md).</summary>
    IssueSeverity Severity,

    /// <summary>Which domain flagged this issue.</summary>
    string Category,

    /// <summary>True if a guided fix flow exists in the Repairs section.</summary>
    bool CanFix,

    /// <summary>
    /// Confidence level for the finding.
    /// Low confidence issues are shown with appropriate caveats.
    /// </summary>
    IssueConfidence Confidence = IssueConfidence.High
);

public enum IssueSeverity
{
    Informational,
    Low,
    Moderate,
    High,
    Critical
}

public enum IssueConfidence
{
    Low,
    Medium,
    High,
    VeryHigh
}

public static class SystemIssueMock
{
    /// <summary>Realistic mock issues for Phase 1 Dashboard display.</summary>
    public static IReadOnlyList<SystemIssue> GetMockIssues() =>
    [
        new SystemIssue(
            Title:       "Several startup apps are slowing your boot time",
            Description: "12 applications launch automatically when Windows starts. " +
                         "Disabling the ones you don't need at startup could reduce boot time by an estimated 8–12 seconds.",
            Severity:    IssueSeverity.Moderate,
            Category:    "Performance",
            CanFix:      true,
            Confidence:  IssueConfidence.High
        ),
        new SystemIssue(
            Title:       "Your SSD is 67% full",
            Description: "Your primary drive has 167 GB of free space remaining. " +
                         "Performance may decrease noticeably once available space drops below 10%.",
            Severity:    IssueSeverity.Low,
            Category:    "Storage",
            CanFix:      false,
            Confidence:  IssueConfidence.VeryHigh
        ),
    ];
}
